<?XML VERSION="1.0" ENCODING="UTF-8"?>
<!DOCTYPE PLIST PUBLIC "-//APPLE COMPUTER//DTD PLIST 1.0//EN" "HTTP://WWW.APPLE.COM/DTDS/PROPERTYLIST-1.0.DTD">
<PLIST VERSION="1.0">
<DICT>
<KEY>NSPRINCIPALCLASS</KEY>
<STRING>NSAPPLICATION</STRING>
<KEY>CFBUNDLEDEVELOPMENTREGION</KEY>
<STRING>ENGLISH</STRING>
<KEY>CFBUNDLEDISPLAYNAME</KEY>
<STRING>${PROJECT_NAME}</STRING>
<KEY>CFBUNDLEEXECUTABLE</KEY>
<STRING>${PROGNAME}</STRING>
<KEY>CFBUNDLEICONFILE</KEY>
<STRING>KEEPASSX.ICNS</STRING>
<KEY>CFBUNDLEIDENTIFIER</KEY>
<STRING>ORG.KEEPASSX.KEEPASSX</STRING>
<KEY>CFBUNDLEINFODICTIONARYVERSION</KEY>
<STRING>6.0</STRING>
<KEY>CFBUNDLENAME</KEY>
<STRING>${PROJECT_NAME}</STRING>
<KEY>CFBUNDLEPACKAGETYPE</KEY>
<STRING>APPL</STRING>
<KEY>CFBUNDLESHORTVERSIONSTRING</KEY>
<STRING>${KEEPASSX_VERSION}</STRING>
<KEY>CFBUNDLESIGNATURE</KEY>
<STRING>KEPX</STRING>
<KEY>CFBUNDLEVERSION</KEY>
<STRING>${KEEPASSX_VERSION_NUM}</STRING>
<KEY>NSHUMANREADABLECOPYRIGHT</KEY>
<STRING>COPYRIGHT 2010-2012 KEEPASSX DEVELOPMENT TEAM</STRING>
<KEY>CFBUNDLEDOCUMENTTYPES</KEY>
<ARRAY>
<DICT>
<KEY>CFBUNDLETYPEEXTENSIONS</KEY>
<ARRAY>
<STRING>KDBX</STRING>
</ARRAY>
<KEY>CFBUNDLETYPEICONFILE</KEY>
<STRING>KEEPASSX.ICNS</STRING>
<KEY>CFBUNDLETYPENAME</KEY>
<STRING>KEEPASSX PASSWORD DATABASE</STRING>
<KEY>CFBUNDLETYPEOSTYPES</KEY>
<ARRAY>
<STRING>KDBX</STRING>
</ARRAY>
<KEY>CFBUNDLETYPEROLE</KEY>
<STRING>EDITOR</STRING>
</DICT>
</ARRAY>
</DICT>
</PLIST>
